name: Back-End of Node JS Application - CI

on: [push]
  # # trigger on pull_request events
  # pull_request:
  #   # On the main branch
  #   branches:
  #     - main 
  #   # Only when code in fronted application changes
  #   paths:
  #     - 'starter/frontend/**'
  

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./starter/backend/

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3
    
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       node-version: '3.10'

  #   - name: Install pipenv packages
  #     run: pip install pipenv

  #   - name: Install Dependencies
  #     run: pipenv install

  #   - name: Run the tests
  #     run: pipenv run test

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        node-version: '3.10'

    # - name: Install pipenv packages
    #   run: pip install pipenv

    # - name: Install Dependencies
    #   run: pipenv install

    # - name: Install essential python packages
    #   run: pipenv install -r Pipfile.txt

    - name: Run the tests
      run: ls -l
  # build:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./starter/backend/

  #   needs: [lint, test]   # This job depends on the "build" job

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       node-version: '3.10'
    
  #   - name: Install pipenv packages
  #     run: pip install pipenv

  #   - name: Install Dependencies
  #     run: pipenv install

  #   - name: Run application
  #     run: pipenv run serve