name: Back End of Node JS Application - CD
on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'starter/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        node-version: '3.10'

    - name: Install pipenv packages
      run: pip install pipenv

    - name: Install Dependencies
      run: pipenv install

    - name: Run the tests
      run: pipenv run test
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend/

    needs: [lint, test]   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        node-version: '3.10'
    
    - name: Install pipenv packages
      run: pip install pipenv

    - name: Install Dependencies
      run: |
        pipenv install
        pipenv install flake8

    - name: Run application
      run: pipenv run serve

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build the image
    #   run: |
    #     docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-backend:${{ github.sha }} .
    #     docker run --name mp-backend -p 3000:3000 -d mp-backend:${{ github.sha }}

  apply-k8s:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend/k8s/

    needs: build   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.15.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Kubeconfig Auth
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Apply the manifests to the cluster
      run: |
        kustomize build | kubectl apply -f -
    


    
