name: Front End of Node JS Application - CD
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'starter/frontend/**'

jobs:
  test:
    name: 'Terraform'
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner
    defaults:
      run:
        working-directory: ./starter/frontend/k8s/

    steps:
      # Check out the code to the runner
      - name: Checkout Repository
        uses: actions/checkout@v3
  
  build:
    runs-on: ubuntu-latest

    needs: test   # This job depends on the "test" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

  deploy-ecr:
    runs-on: ubuntu-latest

    needs: build   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: prj4-capstone/front-end:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        kubectl apply -f deployment.yml --kubeconfig=kubeconfig.yaml
    
