name: Front End of Node JS Application - CD
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'starter/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test # Adjust the test script as per your project

    - name: Check Test Exit Code
      id: test-results
      run: echo "::set-output name=exit-code::${?}"

    - name: Fail the Job on Test Failure
      if: steps.test-results.outputs.exit-code != '0'
      run: exit 1
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend/

    needs: test   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: npm ci

    - name: Build the image
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
        docker run --name mp-frontend -p 3000:3000 -d mp-frontend]


  deploy-ecr:
    runs-on: ubuntu-latest

    needs: build   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: prj4-capstone/front-end:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        kubectl apply -f deployment.yml --kubeconfig=kubeconfig.yaml
    
