name: Front End of Node JS Application - CI

on: [push]
  # # trigger on pull_request events
  # pull_request:
  #   # On the main branch
  #   branches:
  #     - main 
  #   # Only when code in fronted application changes
  #   paths:
  #     - 'starter/frontend/**'
  

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install Dependencies
      run: npm install

    - name: check code with eslint rules
      run: npm run lint
      
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test # Adjust the test script as per your project

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend/

    needs: [lint, test]   # This job depends on the "build" job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run Tests
      run: npm run test # Adjust the test script as per your project

    - name: Run local development server with hot reloading and point to the backend default
      run: REACT_APP_MOVIE_API_URL=http://localhost:5000 npm start